version: '3'
services:
  # server:
  #   build: .
  #   ports:
  #     - ${PORT}:5000
  #   env_file:
  #     - .env
  #   environment:
  #     DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@moovies_db:5432/${DB_NAME}
  #   depends_on:
  #     - moovies_db
  #   restart: on-failure
  #   container_name: api
  db:
    image: postgres:alpine
    env_file:
      - .env
    restart: always
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: moovies_db
volumes:
  db-data:
