version: '3'
services:
  server:
    build: .
    ports:
      - ${PORT}:5000
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@movies_db:27017/${DB_NAME}
    depends_on:
      - movies_db
    restart: on-failure
    container_name: api
